HTD Ingresos = 
// Si necesitas cambiar el separador de lista de esta expresión de Punto y Coma (;) a Coma (,), por favor:
// Abra este archivo con DAX Studio (https://daxstudio.org/) y utilce el comando: Swap Delimertes y luego
// Copie y pegue la expresión desde el propio DAX Studio.
CALCULATE (
    "REFERENCA_A_TU_MEDIDA_AQUÍ" ;
    FILTER (
        ALL ( Calendario[Fecha] ) ;
        Calendario[Fecha] <= MAX ( Calendario[Fecha] ) 
    ) ;
    ALL ( Calendario )
)